algoritmo "exec03"
var
       NOME:caractere
       SALARIO:real
inicio

      Escreval("Qual seu nome ?")
      Leia(NOME)
      Escreval("Qual seu salário ?")
      Leia(SALARIO)
      
      Escreval("O nome do funcionário é: ",NOME)
      Escreval("O salário dele é: ",SALARIO," reais")
      Escreval("O funcionário se chama: ",NOME,", e ele ganha:",SALARIO," reais")


fimalgoritmo
